This notebook is based on "Data Analysis with Python Course - Numpy Introduction A" <br>

https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-course/numpy-introduction-a <br>
https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-course/numpy-introduction-b

In [165]:
import numpy as np
import sys

In [166]:
(2**256)/8

1.4474011154664524e+76

In [167]:
x=5

In [168]:
np.int

int

Continue from here: <br>
https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-course/numpy-arrays

In [169]:
a = np.array([1,2,3,4])
b = np.array([0,.5,1,1.5,2])

In [170]:
a[0], a[1]

(1, 2)

In [171]:
a[0:]

array([1, 2, 3, 4])

In [172]:
a[1:3]

array([2, 3])

In [173]:
a[1:-1]

array([2, 3])

In [174]:
a[::2]

array([1, 3])

In [175]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [176]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In numpy the above is same as:

In [177]:
b[[0,2,-1]]

array([0., 1., 2.])

<h2>Array Types</h2>

In [178]:
a

array([1, 2, 3, 4])

In [179]:
a.dtype

dtype('int32')

In [180]:
b.dtype

dtype('float64')

<h3 style="color: red" >It is important to define the type of data in order to help NumPy work efficiently. </h3> <br> 
    To change type of a data in arrays use following command:

In [181]:
np.array([1, 2, 3, 4], dtype=np.float)

array([1., 2., 3., 4.])

<p>It is possible to store string in NumPy array but there is no point of it, as NumPy cannot take advantage of that.</p>

In [182]:
c = np.array(['a','b','c','d'])

In [183]:
c.dtype

dtype('<U1')

In [184]:
d = np.array([{'a': 1}, sys])

In [185]:
d.dtype

dtype('O')

<h2>Dimensions and shapes</h2>

In [186]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [187]:
A.shape

(2, 3)

In [188]:
A.ndim

2

In [189]:
A.size

6

<h3> 3-Dimentional Array </h3>

In [190]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
    ])

In [191]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [192]:
B.shape

(2, 2, 3)

In [193]:
B.ndim

3

In [194]:
B.size

12

<h4>If the shape isn't consistent, it'll just fall back to regular Python objects: </h4>

In [195]:
C = np.array([
    [
        [11, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

C:\Dokumenty\PROJ_PY39\003_DataAnalPy\cnd_env\lib\site-packages\ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  import sys


In [196]:
C.dtype

dtype('O')

In [197]:
C.shape

(2,)

In [198]:
C.size

2

In [199]:
type(C[0])

list

<h2> Indexing and Slicing of Matrices</h2>

In [200]:
# Square matrix
A = np.array([
#   C0 C1 C2
    [1, 2, 3], # R0
    [4, 5, 6], # R1
    [7, 8, 9]  # R2
])

In [201]:
A[1] # R1

array([4, 5, 6])

In [202]:
A[1][0]  # R1C0 Python Way

4

In [203]:
A[1, 0]  #R1C0 NumPy Way, Advantage of that method allows you to add slicing (below)

4

In [204]:
A[0:2] # Slicing - Show from Dim1 (Row) from 0 to 2

array([[1, 2, 3],
       [4, 5, 6]])

In [205]:
A[:, :2] # Slicing - Show every row but only columns from the begining to second column or C1

array([[1, 2],
       [4, 5],
       [7, 8]])

In [206]:
A[:2, :2] # Slicing - Show rows from first to second R1 and only columns from the begining to second column or C1

array([[1, 2],
       [4, 5]])

In [207]:
A[:2, 2:] # Slicing - Show rows from first to second R1 and only columns from second column or C1 to last column

array([[3],
       [6]])

In [208]:
A[1] = np.array([10, 10, 10]) # Change second row R index [1] values to 10

In [209]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [210]:
A[2] = 99

In [211]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

<h2>Summary Statistics</h2>

In [212]:
a = np.array([1, 2, 3, 4])

In [213]:
a.sum()

10

In [214]:
a.mean()

2.5

In [215]:
a.std()

1.118033988749895

In [216]:
a.var()

1.25

In [217]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [218]:
a.sum()

10

In [219]:
a.mean()

2.5

In [220]:
a.std()

1.118033988749895

In [221]:
a.sum()

10

In [222]:
A.sum(axis=0)

array([12, 15, 18])

In [223]:
A.sum(axis=1)

array([ 6, 15, 24])

In [224]:
A.mean(axis=1)

array([2., 5., 8.])

In [225]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [226]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

<h1> Broadcasting and Vectorized operations </h1>
<br>
<a href="https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-course/numpy-operations" target="_blank" rel="noopener noreferrer">Link to Lecture</a>

In [227]:
a = np.arange(4)

In [228]:
a

array([0, 1, 2, 3])

In [229]:
a + 10

array([10, 11, 12, 13])

In [230]:
a * 10

array([ 0, 10, 20, 30])

In [231]:
a = np.arange(4)

In [232]:
b = np.array([10, 10, 10, 10])

In [233]:
a + b

array([10, 11, 12, 13])

In [234]:
a * b

array([ 0, 10, 20, 30])

<h1> Boolean arrays (Also called masks) </h1>
<br>
<a href="https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-course/numpy-boolean-arrays" target="_blank" rel="noopener noreferrer">Link to Lecture</a>

In [236]:
a = np.arange(4)

In [237]:
a

array([0, 1, 2, 3])

<h4>Boolean arrays - choose elements based on boolean</h4>

In [255]:
a[[True, False, False, True]] # is the same as


array([0, 3])

The above is equivalent to the below

In [242]:
a[[0, -1]]

array([0, 3])

In [243]:
a >= 2

array([False, False,  True,  True])

In [244]:
a[a >= 2]

array([2, 3])

In [245]:
a.mean()

1.5

In [246]:
a[a > a.mean()] # Give me all elements that are greater then mean

array([2, 3])

In [247]:
a[~(a > a.mean())] # Give me all the elements that are not greater then mean

array([0, 1])

In [248]:
a[(a == 0) | (a == 1)]  # Give me all the elements that are 0 OR 1

array([0, 1])

In [257]:
a[(a <= 2) & (a % 2 == 0)] # Give all numbers that are less or equal to 2 AND are even numbers

array([0, 2])

In [259]:
print( a <= 3)

[ True  True  True  True]


In [260]:
A = np.random.randint(100, size=(3,3))

In [262]:
A

array([[27,  2, 83],
       [15, 73, 80],
       [83, 59, 93]])

In [263]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([27, 83, 73, 83, 93])

In [264]:
A > 30

array([[False, False,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [265]:
A[A > 30]

array([83, 73, 80, 83, 59, 93])

<h1> Linear Algebra </h1>
<br>
<a href="https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-course/numpy-algebra-and-size" target="_blank" rel="noopener noreferrer">Link to Lecture</a>

In [267]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [268]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [269]:
# Numpy size is much smaller
np.dtype(int).itemsize

4

In [270]:
np.dtype(float).itemsize

8

<h4>Lists are even larger</h4>

In [272]:
# A one-element list
sys.getsizeof([1])

72

In [274]:
# An array of one element in numpy
np.array([1]).nbytes

4

<h4>And performance is also important</h4>

In [280]:
a = np.arange(1000)
%time np.sum(a ** 2) # NumPy Way - FASTER

Wall time: 0 ns


332833500

In [282]:
l = list(range(1000))
%time sum([x ** 2 for x in l])# Python way - SLOWER

Wall time: 0 ns


332833500

<h4>Useful Numpy functions</h4>

<h6 style="font-family:georgia,garamond,serif; font-size:16px;font-style:italic;background-color: #FFFF00">random</h6>

In [283]:
np.random.random(size = 2)

array([0.8178717 , 0.09223277])

In [284]:
np.random.normal(size = 2)

array([-0.2177428 ,  0.82738427])

In [285]:
np.random.rand(2,4)

array([[0.37886938, 0.50967419, 0.73458748, 0.37386721],
       [0.49653976, 0.82703697, 0.86761961, 0.31654092]])

<h6 style="font-family:georgia,garamond,serif; font-size:16px;font-style:italic;background-color: #FFFF00">arange</h6>

In [286]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [287]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [288]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

<h6 style="font-family:georgia,garamond,serif; font-size:16px;font-style:italic;background-color: #FFFF00">reshape</h6>

In [290]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [291]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

<h6 style="font-family:georgia,garamond,serif; font-size:16px;font-style:italic;background-color: #FFFF00">linespace</h6>

In [293]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [294]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [297]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

<h6 style="font-family:georgia,garamond,serif; font-size:16px;font-style:italic;background-color: #FFFF00">zeros, ones, empty</h6>

In [299]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [300]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [302]:
np.zeros((3, 3), dtype=np.int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [303]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [304]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [305]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [306]:
np.empty((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

<h6 style="font-family:georgia,garamond,serif; font-size:16px;font-style:italic;background-color: #FFFF00">indentify and eye</h6>

In [308]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [309]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [310]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [311]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [312]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [314]:
"Hello World"[6]

'W'